### ISSUE TITLE
行内代码块改用更加醒目的红色样式

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#117]
dark+目前对clt+G 行内代码的样式处理就是加了一个灰色背景。这种处理不是很醒目，特别是在整篇文档中翻看的时候，一时间难以识别出这是一段代码。
或许可以采用zhanglight这种更加醒目的处理方式(≧∇≦)ﾉ
![QQ截图20221012152213](https://user-images.githubusercontent.com/37429029/195277057-fc33b2c6-f45c-4edf-8081-9b338648c7d6.png)
![QQ截图20221012152232](https://user-images.githubusercontent.com/37429029/195277525-48bc86c6-1e04-4601-a119-e0ceb6742493.png)

**Comment by Zuoqiu-Yingyi** [comment]
可以使用如下片段自定义行内代码的颜色与背景为 zhang-light 的颜色
```css
.protyle-wysiwyg code:not(.hljs),
.b3-typography code:not(.hljs),
.protyle-wysiwyg span[data-type~=code]:not(.hljs),
.b3-typography span[data-type~=code]:not(.hljs) {
  color: #cf5659;
  background-color: #f8ecec;
}

```
