### ISSUE TITLE
隐藏底部数据仓库同步信息

### ISSUE THREAD

**Issue by yuyuyu-github** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#118]
使用dark+在记笔记的过程中，发现系统进行同步的时候，底部地数据就会刷刷刷地更新，这种动态变化在静态地笔记中尤为显眼，经常被打断注意力。 

![QQ截图20221012152940](https://user-images.githubusercontent.com/37429029/195278775-031e5c97-d7cd-40ca-a1cb-8e1fafa8c3bc.png)

是否可以隐藏底部的同步信息？

![image](https://user-images.githubusercontent.com/37429029/195278262-45d4a7c5-4cec-40d5-9629-7793f9cf2786.png)

**Comment by Zuoqiu-Yingyi** [comment]
使用如下 css 片段
```css
#status>.status__msg {
    display: none;
}

```
