### ISSUE TITLE
固定页签省去文字

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#126]
功能请求：专注模式中，含有图标的固定页签省去文字，节省屏幕空间

文档标题有图标且被pin的时候，页签只显示图标，类似集市中notion-theme主题（或者默认主题native）的效果，这种对于专注模式或者类似onenote的快速笔记模式比较友好。

我查到文件 D:\SiYuan\conf\appearance\themes\Dark+\style\module\tab-bar.css ，

```css
.layout-tab-bar .item.item--pin .item__text {
  /* 钉住的标签页文本全部显示 */
  width: auto;
  max-width: none;
  display: flex !important;
}
```

但是不知道怎么修改才能达到这个目的，或者专注模式无法达到这个目的？

谢谢！
