### ISSUE TITLE
:bug: Docker版思源笔记安装主题后，无法和预览图一样显示“霞鹜文楷等宽”字体

### ISSUE THREAD

**Issue by lfk2458** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#172]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Docker版思源笔记安装主题后，无法和预览图一样显示“霞鹜文楷等宽”字体

### 期待的结果 Expected result

Docker版思源笔记安装主题后，能和预览图一样正常显示“霞鹜文楷等宽”字体

### 版本环境 Version environment

```markdown
- SiYuan Version: V2.6.2
- Dark+ Version: v1.6.3
- Operating System: Docker version 19.03.9
- Browser (if used):
```

**Comment by Zuoqiu-Yingyi** [comment]
这是思源的限制, 浏览器访问的 web 端只能使用默认的字体或者使用主题 / CSS 片段设置字体

**Comment by lfk2458** [comment]
那请问需要如何修改主题的默认字体呢？我想把字体修改为“霞鹜文楷等宽”字体

**Comment by Zuoqiu-Yingyi** [comment]
使用如下 CSS 片段
```css
.b3-typography:not(.b3-typography--default),
.protyle-wysiwyg,
.protyle-title,
.protyle-title__input {
    font-family: "霞鹜文楷等宽", "quote", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols" !important;
}

```
