### ISSUE TITLE
行内代码样式修改建议:sparkles: 

### ISSUE THREAD

**Issue by huamang** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#173]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我使用light下的Dark+主题，发现行内代码其实不太明显
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/73064480/212529002-e7481c12-4dfa-47be-a7c7-3f6c51eacf86.png">

所以我尝试模仿了几个博客中行内代码的配色，觉得这样展示行内代码会比较清晰
<img width="928" alt="image" src="https://user-images.githubusercontent.com/73064480/212528964-0fd579c7-091a-41aa-b705-9f18abde085f.png">

### 描述可能的最优解决方案 Describe the optimal solution

以下是我对于这次样式修改的css代码
```css
:root {
/* 行内代码背景颜色 */
  --b3-protyle-code-background: rgba(27,31,35,0.05);
}
/* 行内字体代码 */
.protyle-wysiwyg code:not(.hljs),
.b3-typography code:not(.hljs),
.protyle-wysiwyg span[data-type~=code]:not(.hljs),
.b3-typography span[data-type~=code]:not(.hljs) {
color: #f47466;
}
```
