### ISSUE TITLE
很喜欢您做得主题，请问您有没有考虑给已经完成的待办添加删除线呢？

### ISSUE THREAD

**Issue by Lyn6969** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#2]
您好！我经常在思源笔记中使用任务列表，但是目前的任务列表点击完成之后只有前面打上了对钩，看起来不是很清晰。而类似滴答清单等to-do软件一般会在待办完成后添加删除线以突出显示。所以我想请问您是否有考虑给已完成待办添加删除线呢？如果您不方便或者不想添加，我想请教一下该如何在本地修改代码，我不是特别懂css，麻烦您了！

**Comment by Zuoqiu-Yingyi** [comment]
@Lyn6969 请问想要什么样子的删除线, 我发现其他主题主要有两种实现方案
1. 仅在 **当前列表项** 中显示删除线
2. 在 **当前列表项** 及其 **子列表项** 中显示删除线

**Comment by Lyn6969** [comment]
> @Lyn6969 请问想要哪种方案的删除线呀❓ 我发现其他主题主要有两种实现方案
> 
> 1. 仅在 **当前列表项** 中显示删除线
> 2. 在 **当前列表项** 及其 **子列表项** 中显示删除线

第二种吧，我也看到了Tsunduku的代码，他那个还带调了一下透明度的。

**Comment by Zuoqiu-Yingyi** [comment]
@Lyn6969 刚刚发现第二种有一些问题, 在任务列表项的下一级可能存在其他列表, 比如有序列表与无序列表, 我

**Comment by Lyn6969** [comment]
> @Lyn6969 刚刚发现第二种有一些问题, 在任务列表项的下一级可能存在其他列表, 比如有序列表与无序列表, 我, 虽然可以只在次级的任务列表项显示删除线, 但风格就不统一了

没事不急不急，只是提一个想法，如果麻烦的话第一种也可以

**Comment by Zuoqiu-Yingyi** [comment]
@Lyn6969 实现没啥问题, 只是不美观, 不过你想使用第二种方案的话可以将如下 CSS 片段塞到文件 `<工作区>\data\widgets\custom.css` 中即可(如果没有该文件请新建)

```css
div[data-node-id].li.protyle-task--done div[data-node-id].p {
    text-decoration: line-through var(--b3-theme-on-surface);
    color: var(--b3-theme-on-surface);
}
```
