### ISSUE TITLE
Tab 显示 限制文字个数

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#205]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

因为工作流的原因有一些标题很长的文档，当打开这些文档时，Tab显得不太舒服 
另外，有些主题对于Tab，当有图标时，只显示一个图标，这种也是比较精简的

### 描述可能的最优解决方案 Describe the optimal solution

允许用户设置标题显示文字的字符长度上限，
1. 如果是“0”字符，那就是不显示文档标题，只显示图标；
2. 如果文档标题超过这个上限，那么对标题按照设置值进行截取显示；
3. 如果文档标题没有超过这个上限，那么标题文字全部显示；

### 其他信息 Other information

可能代码片段也能解决这个问题

**Comment by Zuoqiu-Yingyi** [comment]
这个是主题特性, 目的是为用户提供完整信息
不过如果想设置文字个数, 可以使用如下代码片段

```css
.layout-tab-bar .item .item__text {
    max-width: 16em;
    text-overflow: ellipsis;
}

.layout-tab-bar .item .item__icon + .item__text {
    max-width: 0;
}

```

- `16em` 表示没有图标的文档仅显示标题中前 16 个全宽字符
- `0` 表示有图标的文档不显示标题
