### ISSUE TITLE
是否可以关闭浮窗透明功能

### ISSUE THREAD

**Issue by aptexd** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#33]
开发这你好
当鼠标放到引用块上时会有弹窗弹出内容
弹窗可能是为了和全局统一，也是透明得
这样弹窗内容会和背景文档重合在一起，多级浮窗会重叠得更厉害
这样十分不利于阅读和编辑
不知开发者能否将浮窗设置为不透明，或者增加设置选项，即使全局不透明也可以

**Comment by Zuoqiu-Yingyi** [comment]
浮窗透明颜色是有 CSS 变量 `--custom-popover-background-color` 控制的, 可以使用如下方案自定义
1. 新建文件 `data\widgets\custom-dark.css` 与 `data\widgets\custom-light.css`, 这两个文件分别是暗色与亮色的用户自定义配置文件
2. 在该文件中添加如下内容
```css
:root {
    --custom-popover-background-color: <想要设置的颜色颜色>;
}
```
3. 分别设置想要的不透明颜色
