### ISSUE TITLE
如何自定义/移除空行提示 `这里是空的 (´･-･)ﾉ`

### ISSUE THREAD

**Issue by xiaoxiaozhongyi** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#37]
请问大佬可以去掉“这里是空的”的提示吗？
感觉加上这个提示之后有点乱
![image](https://user-images.githubusercontent.com/53644808/167280194-fa63f822-8769-438a-bb15-b26afdc6731b.png)

**Comment by Zuoqiu-Yingyi** [comment]
1. 打开文件 `<工作空间>/data/widgets/custom.css`, 如果没有则新建
2. 在文件中写入如下内容, 之后修改为想要的空行提示文本, 如果不想该文本, 设置为空字符串 `""`
      ```css
      :root {
          --custom-empty-p: "这里是空的 (´･-･)ﾉ㊫";
          --custom-empty-c: "这里是空的 (´･-･)ﾉ↹";
          --custom-empty-t: "这里是空的 (´･-･)ﾉ☑";
          --custom-empty-u: "这里是空的 (´･-･)ﾉ◉";
          --custom-empty-o: "这里是空的 (´･-･)ﾉ①";
      }
      ```
3. 保存文件并使用 `Ctrl + F5` 重新加载页面
