### ISSUE TITLE
建议：折叠样式的标记改到首行的内容前面，不要换行

### ISSUE THREAD

**Issue by o-ut-man** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#43]
<img width="148" alt="Snipaste_2022-05-12_16-11-40" src="https://user-images.githubusercontent.com/34265164/168023846-6810688f-7c52-481c-93bc-2f145e6f2614.png">
可以改成类似这种
<img width="127" alt="Snipaste_2022-05-12_16-14-03" src="https://user-images.githubusercontent.com/34265164/168024158-312e4ef2-62d5-4a82-ab28-655a0485fd0d.png">

**Comment by Zuoqiu-Yingyi** [comment]
抱歉, 当前方案是之前群友投票的结果😂, 不过可以参考 README.md 中的 [#custom.css](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#customcss) 进行自定义, 自定义内容也可以随工作空间同步

**Comment by guidongyuan** [comment]
> 

大佬，有个傻瓜式的教程可以看看怎样修改，目前那个占用了一行，确实看起来有点怪怪

**Comment by Zuoqiu-Yingyi** [comment]
> > 
> 
> 大佬，有个傻瓜式的教程可以看看怎样修改，目前那个占用了一行，确实看起来有点怪怪

```css
.protyle-wysiwyg [data-node-id][fold="1"][data-type="NodeHeading"]::after {
  /* 移除子标题折叠原有样式 */
  content: none;
}
.protyle-wysiwyg [data-node-id][fold="1"][data-type="NodeHeading"]::before {
  /* 添加子标题折叠标记 */
  content: var(--custom-h-fold-mark);
  font-size: 100%;
}
```
