### ISSUE TITLE
不同级别标题前面的颜色是按照什么顺序排的？

### ISSUE THREAD

**Issue by Geo123abc** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#48]
大纲视图和正文中的标题颜色是按照什么顺序排的（黑蓝黄绿红紫）？个人习惯吗？

PS：-p，-c，-t，-u，-o，这个提示的有什么区别啊？ 我笔记里面都是 -p的效果
    --custom-empty-p: "这里是空的 (´･-･)ﾉ㊫";
    --custom-empty-c: "这里是空的 (´･-･)ﾉ↹";
    --custom-empty-t: "这里是空的 (´･-･)ﾉ☑";
    --custom-empty-u: "这里是空的 (´･-･)ﾉ◉";
    --custom-empty-o: "这里是空的 (´･-･)ﾉ①";

**Comment by Zuoqiu-Yingyi** [comment]
- `--custom-empty-p`: 空段落块
- `--custom-empty-c`: 空代码块
- `--custom-empty-t`: 空任务列表项
- `--custom-empty-u`: 空无序列表项
- `--custom-empty-o`: 空有序列表项

**Comment by Geo123abc** [comment]
> * `--custom-empty-p`: 空段落块
> * `--custom-empty-c`: 空代码块
> * `--custom-empty-t`: 空任务列表项
> * `--custom-empty-u`: 空无序列表项
> * `--custom-empty-o`: 空有序列表项

谢谢，那个标题颜色排序呢？

**Comment by Zuoqiu-Yingyi** [comment]
> 谢谢，那个标题颜色排序呢？

是为了增加对比度, 暖色冷色相间排列的
可以通过如下 6 个 CSS 变量自定义

--custom-h1-color
--custom-h2-color
--custom-h3-color
--custom-h4-color
--custom-h5-color
--custom-h6-color

**Comment by Geo123abc** [comment]
> 

好的，如果是为了增加对比度，可能彩虹色这样的就不太合适了，那我还是自己改一下吧，谢谢

**Comment by Geo123abc** [comment]
@Zuoqiu-Yingyi  根绝你的提示，我新建了文件“<工作空间>/data/widgets/custom.css”，内容如下（调整子标题及对应的大纲色、取消空行提示），但是没有效果，能麻烦帮忙看下那个地方不对吗？


/* 配置文件 */
/* 
## 自定义配置方法 | CUSTOM CONFIG METHOD

1. 创建文件 `<工作空间>/data/widgets/custom.css`  
   Create a file `<workspace>/data/widgets/custom.css`
2. 在文件 `<工作空间>/data/widgets/custom.css` 中定义的值将覆盖 `<工作空间>/conf/appearance/themes/Dark+/style/module/config.css` 中对应的值  
   The value defined in file `<workspace>/data/widgets/custom.css` overwrites the corresponding value in file `<workspace>/conf/appearance/themes/Dark+/style/module/config.css`.
*/

/* 导入基础配色(如果需要导入其他配色, 请修改 URL) */
/* @import url(/appearance/themes/midnight/theme.css); */

/* 自定义属性 */
:root {

    /* 子标题及其对应大纲颜色 | Subheadings and their corresponding outline colors *,彩虹色/
    --custom-h1-color: var(--b3-card-error-color);
    --custom-h2-color: var(--b3-card-warning-color);
    --custom-h3-color: #F2F279;
    --custom-h4-color: var(--b3-card-success-color);
    --custom-h5-color: var(--b3-card-info-color);
    --custom-h6-color: var(--custom-color-8-3);

    /* 空行聚焦提示 | Blank line focus prompt */
    --custom-empty-focus-p: ;
    --custom-empty-focus-c: "´･-･)ﾉ↹";
    --custom-empty-focus-t: "´･-･)ﾉ☑";
    --custom-empty-focus-u: "´･-･)ﾉ◉";
    --custom-empty-focus-o: "´･-･)ﾉ①";

    /* 空行提示 | Blank line prompt */
    --custom-empty-p: ;
    --custom-empty-c: "这里是空的 (´･-･)ﾉ↹";
    --custom-empty-t: "这里是空的 (´･-･)ﾉ☑";
    --custom-empty-u: "这里是空的 (´･-･)ﾉ◉";
    --custom-empty-o: "这里是空的 (´･-･)ﾉ①";
}

**Comment by Zuoqiu-Yingyi** [comment]
如果取消空行提示的话需要将变量设置为空字符串
```css
:root {
    /* 子标题及其对应大纲颜色 | Subheadings and their corresponding outline colors *,彩虹色/
    --custom-h1-color: var(--b3-card-error-color);
    --custom-h2-color: var(--b3-card-warning-color);
    --custom-h3-color: #F2F279;
    --custom-h4-color: var(--b3-card-success-color);
    --custom-h5-color: var(--b3-card-info-color);
    --custom-h6-color: var(--custom-color-8-3);
    
    /* 空行聚焦提示 | Blank line focus prompt */
    --custom-empty-focus-p: "";
    --custom-empty-focus-c: "´･-･)ﾉ↹";
    --custom-empty-focus-t: "´･-･)ﾉ☑";
    --custom-empty-focus-u: "´･-･)ﾉ◉";
    --custom-empty-focus-o: "´･-･)ﾉ①";
    
    /* 空行提示 | Blank line prompt */
    --custom-empty-p: "";
    --custom-empty-c: "这里是空的 (´･-･)ﾉ↹";
    --custom-empty-t: "这里是空的 (´･-･)ﾉ☑";
    --custom-empty-u: "这里是空的 (´･-･)ﾉ◉";
    --custom-empty-o: "这里是空的 (´･-･)ﾉ①";
}
```

**Comment by Geo123abc** [comment]
> ```css
> 子标题及其对应大纲颜色
> ```

空行提示解决了，但是大纲颜色还是没变

**Comment by Zuoqiu-Yingyi** [comment]
> 空行提示解决了，但是大纲颜色还是没变

哦哦, 不好意思, 代码注释的格式有点问题, 我刚刚重新编辑了上一个回复

**Comment by Geo123abc** [comment]
> > 空行提示解决了，但是大纲颜色还是没变
> 
> 哦哦, 不好意思, 代码注释的格式有点问题, 我刚刚重新编辑了上一个回复

我又试了一下，但是还是有些颜色不能使用，我决定使用固定颜色值（取自你的主题中  /* 自定义标准颜色(Office 标准颜色) */），但是还是不能完全正确显示


:root {
    /* 子标题及其对应大纲颜色 */
    --custom-h1-color: #FA0000;
    --custom-h2-color: #FFC001;
    --custom-h3-color: #F2F279;
    --custom-h4-color: #00B050;
    --custom-h5-color: #00B0F0;
    --custom-h6-color: #7030A0;
    
    /* 空行聚焦提示 */
    --custom-empty-focus-p: "";
    --custom-empty-focus-c: "´･-･)ﾉ↹";
    --custom-empty-focus-t: "´･-･)ﾉ☑";
    --custom-empty-focus-u: "´･-･)ﾉ◉";
    --custom-empty-focus-o: "´･-･)ﾉ①";
    
    /* 空行提示 */
    --custom-empty-p: "";
    --custom-empty-c: "这里是空的 (´･-･)ﾉ↹";
    --custom-empty-t: "这里是空的 (´･-･)ﾉ☑";
    --custom-empty-u: "这里是空的 (´･-･)ﾉ◉";
    --custom-empty-o: "这里是空的 (´･-･)ﾉ①";
}


显示效果
![](https://s3.bmp.ovh/imgs/2022/05/14/ae48df936fe15f45.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 我又试了一下，但是还是有些颜色不能使用，我决定使用固定颜色值（取自你的主题中 /* 自定义标准颜色(Office 标准颜色) */），但是还是不能完全正确显示

颜色有两套, 分别是暗色主题的颜色与亮色主题的颜色, 如果你想要自定义亮色主题的颜色, 那么需要新建文件 `widgets/custom-light.css` 并写入你的自定义颜色
```css
:root {
    /* 子标题及其对应大纲颜色 */
    --custom-h1-color: #FA0000;
    --custom-h2-color: #FFC001;
    --custom-h3-color: #F2F279;
    --custom-h4-color: #00B050;
    --custom-h5-color: #00B0F0;
    --custom-h6-color: #7030A0;
}
```

**Comment by Geo123abc** [comment]
> > 我又试了一下，但是还是有些颜色不能使用，我决定使用固定颜色值（取自你的主题中 /* 自定义标准颜色(Office 标准颜色) */），但是还是不能完全正确显示
> 
> 颜色有两套, 分别是暗色主题的颜色与亮色主题的颜色, 如果你想要自定义亮色主题的颜色, 那么需要新建文件 `widgets/custom-light.css` 并写入你的自定义颜色
> 
> ```css
> :root {
>     /* 子标题及其对应大纲颜色 */
>     --custom-h1-color: #FA0000;
>     --custom-h2-color: #FFC001;
>     --custom-h3-color: #F2F279;
>     --custom-h4-color: #00B050;
>     --custom-h5-color: #00B0F0;
>     --custom-h6-color: #7030A0;
> }
> ```

soga！成功了，谢谢！
那么下次更新这段说明是否要备注一下custom-light.css 和custom-dark.css（？）命名区别？

2. 在文件 `<工作空间>/data/widgets/custom.css` 中定义的值将覆盖 `<工作空间>/conf/appearance/themes/Dark+/style/module/config.css` 中对应的值  
   The value defined in file `<workspace>/data/widgets/custom.css` overwrites the corresponding value in file

**Comment by Zuoqiu-Yingyi** [comment]
> soga！成功了，谢谢！ 那么下次更新这段说明是否要备注一下custom-light.css 和custom-dark.css（？）命名区别？

其实这里写得挺清楚了~ [自定义配置 | CUSTOM CONFIG](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE--custom-config)

**Comment by Geo123abc** [comment]
> > soga！成功了，谢谢！ 那么下次更新这段说明是否要备注一下custom-light.css 和custom-dark.css（？）命名区别？
> 
> 其实这里写得挺清楚了~ [自定义配置 | CUSTOM CONFIG](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE--custom-config)


emmmm,谢谢，最近眼神不好使~~~

**Comment by Zuoqiu-Yingyi** [comment]
背景图 URL 变量是 `--custom-background-image`, 因此在 `custom-light.css` 中设置即可

```css
:root {
    /* 子标题及其对应大纲颜色 */
    --custom-h1-color: #FA0000;
    --custom-h2-color: #FFC001;
    --custom-h3-color: #000000;
    --custom-h4-color: #00B050;
    --custom-h5-color: #00B0F0;
    --custom-h6-color: #7030A0;
    
    /* 空行聚焦提示 */
    --custom-empty-focus-p: "";
    --custom-empty-focus-c: "´･-･)ﾉ↹";
    --custom-empty-focus-t: "´･-･)ﾉ☑";
    --custom-empty-focus-u: "´･-･)ﾉ◉";
    --custom-empty-focus-o: "´･-･)ﾉ①";
  
    /* 空行提示 */
    --custom-empty-p: "";
    --custom-empty-c: "";
    --custom-empty-t: "";
    --custom-empty-u: "";
    --custom-empty-o: "";

    /* 默认背景图片 */
    --custom-background-image: url("/appearance/themes/background (07).png");
}
```
