### ISSUE TITLE
调整标题块 `::before` 伪元素位置

### ISSUE THREAD

**Issue by mdzz2048** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#62]
当前版本（v1.0.3）标题自定义属性显示样式是和标题内容在同一行的，能否改为和段落块一样分行显示？
![image](https://user-images.githubusercontent.com/86549958/170812812-574ef4c5-8a18-43c7-ae09-ee12d5d1c176.png)
![image](https://user-images.githubusercontent.com/86549958/170812815-9b3f04de-b605-40f4-929e-fa1ec68f0d50.png)
![image](https://user-images.githubusercontent.com/86549958/170812832-10611073-369f-440f-b61d-eb16ec9610ba.png)

**Comment by Zuoqiu-Yingyi** [comment]
因为标题的 `::before` 用于自动编号了, 试试使用如下自定义样式

```css
.protyle-wysiwyg>div[data-node-id][data-type="NodeHeading"]::before {
    float: none;
}
```
