### ISSUE TITLE
对题目存疑

### ISSUE THREAD

**Issue by taozina** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#7]
朋友，您的主题构建得非常好。 恭喜。 我只有一个问题（个人口味）。

在标题（h1、h2、h3、h4、h5、h6）中有一个计数（1.1 / 1.1.1 / 1.1.1.1）。 正确的？ 这些数字紧挨着非常小的标题。 如何增加这些数字的大小？

**Comment by Zuoqiu-Yingyi** [comment]
新建文件 `data/widgets/custom.css`，在该文件输入如下内容即可覆盖 `config.css` 中对应的变量，`--custom-h-num-font-size` 是设置编号缩放大小，根据自己需求调整
```css
:root {
    --custom-h-num-font-size: 50%;
}
```
