### ISSUE TITLE
更新后对PDF进行标注，被标注区域出现鬼畜现象

### ISSUE THREAD

**Issue by mybitdock** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#81]

**Comment by Zuoqiu-Yingyi** [comment]
已修复, 如果急用的话使用如下内容覆盖 `/conf/appearance/themes/Dark+/style/module/icon-zoom.css` 文件

```css
/* 引入参数配置 */
@import url(/appearance/themes/Dark+/style/module/config.css);
@import url(/widgets/custom.css);
svg.popover__block:hover {
  transform: scale(1.25);
  transition: all 0.1s ease-in-out;
}
.b3-list-item__icon:hover svg,
.dock__item:hover svg,
.toolbar__item:hover svg,
.block__icon:hover svg {
  transform: scale(1.25);
  transition: all 0.1s ease-in-out;
}

```
